[package]
name = "holdem-rsources"
version = "0.1.0"
edition = "2024"

[dependencies]
criterion = "0.8.1"
serde = { version = "1.0", features = ["derive"] }
ndarray = "0.17.1"
rand = "0.9.2"
rayon = "1.11.0"
thiserror = "2.0.17"
anyhow = "1.0.100"
